spring.application.name=
spring.datasource.url=
spring.datasource.driver-class-name=
spring.sql.init.mode=
spring.datasource.username=
spring.datasource.password=

api.security.token.secret=
spring.jpa.database-platform=
spring.jpa.hibernate.ddl-auto=